### ISSUE TITLE
Adding Pan-Gene-Set-related Filtering Parameters to Gene Query

### ISSUE THREAD

**Issue by That-Thing** [legumeinfo/graphql-server#106]
[Pangene search](https://github.com/legumeinfo/website-ui-specs/tree/main/pangenes-search) requires results to be filtered by pangene and/or accession, which is not supported in the gene query. 

Adding support for filtering by these would remove the necessity to filter manually in the clientside JS.

**Comment by alancleary** [comment]
@sammyjava Would this require implementing a `pangenes` GraphQL query rather than extending the existing `genes` query?

**Comment by sammyjava** [comment]
As for adding a pan-gene set identifier parameter to search-genes, that's easy, it's the same as doing so for gene family identifier. Gene has a `panGeneSets` collection just like its `geneFamilies` collection.

Entering a gene and wanting to see other genes that _belong to the same pan-gene sets as the entered gene_ is also easy. For example, against MiniMine:
```xml
<query name="" model="genomic" view="Gene.panGeneSets.primaryIdentifier Gene.panGeneSets.genes.primaryIdentifier" longDescription="" sortOrder="Gene.panGeneSets.primaryIdentifier asc">
  <constraint path="Gene.primaryIdentifier" op="=" value="phavu.G19833.gnm1.ann1.Phvul.004G025600"/>
</query>
```
That would be a different API method, call it `getGenesInPanGeneSetOfGene`, say.

**Comment by alancleary** [comment]
> Hrm. Actually I don't know how to implement that simple query. It's not on the attributes of a root class, it's on the attributes of members of a collection of a class which is itself in a collection:
> 
> ```
> view="Gene.panGeneSets.genes.primaryIdentifier" [actually all the intermineGeneAttributes]
> ```

So does this affect PR #109?

**Comment by sammyjava** [comment]
> So does this affect PR #109?

Nope, totally separate. PR #109 is/was just adding in a simple filter to the existing searchGenes API method that I'd omitted in 5.1.0.3-model-updates. This query for genes that belong to the pan-gene-sets of a given gene is for a new API method which will be in another branch. If we can figure out how to do it.

**Comment by alancleary** [comment]
Can this issue be closed since we've addressed @That-Thing's requirements?

**Comment by sammyjava** [comment]
Yeah, I guess @That-Thing was referring just to the gene search filter. However, it might be nice to have graphql-server provide the other requirement of the UI spec, which is "genes in the pan-gene-sets of the given gene." Right now you'd have to first get that gene's pan-gene sets, then get the genes for those pan-gene sets, and then prune dupes, all client-side. But although the path query is extremely simple, I don't see how to implement it in our graphql-server framework since it isn't a query on root class attributes. I'm happy to let it rest until it's brought up again. :)

**Comment by alancleary** [comment]
I've been thinking about this and have a follow-up question: Since this is using the `genes` search GraphQL query won't leaving the `panGeneSetIdentifier` blank return non-pangenes as well? I think we may actually need a different query that limits results to only pangenes, whether or not any constraints are given. Furthermore, since pangenes aren't limited to a specific genus, species, accession, etc (i.e. the pangene search parameters) the data-source supporting the query would need to find pangenes  whose gene sets contain at least one gene that meet these constraints. Or am I completely misundering the spec? @StevenCannon-USDA can you clarify?

**Comment by sammyjava** [comment]
Which is fine, but I think the UI should allow only specifying a gene for which to get fellow pan-genes XOR specifying a pan-gene set identifier. Not both.

**Comment by alancleary** [comment]
I think I need some clarification from @StevenCannon-USDA on what exactly the spec is searching for. It seems to me that this is actually a pangene set search, i.e. the results are a unique list of pangene sets, where each set contains one or more genes that meet the Genus, Species, Accession, and Gene ID constraints. The possibly filtered list of genes for each result is just the `genes` field of the `PanGeneSet`.

**Comment by alancleary** [comment]
Thanks for clarifying @StevenCannon-USDA. It sounds like in this case "pangene" is synonymous with "pangene set" and as far as implementing the search functionality goes we're actually interested in the `PanGeneSet` GraphQL type.

Regarding listing the genes in a pangene set, I think it might be worth doing the following:

- Pull in all the genes for each pangene set
    - This allows us to easily get the "Genes in this pangene" number
    - This allows users to see what other genes are in the pangene without necessarily navigating to a different page
    - This will make the GraphQL search implementation much simpler
- Display a pangene's gene set in a modal rather than directly in the results table
    - This will keep the search element from becoming unwieldy when the results have large pangene sets
    - This will allow us to implement control of a pangene's set of genes, such as filtering by the query parameters and reordering the list of genes
    - This will also make the pangene search web component implementation much simpler

**Comment by alancleary** [comment]
> About keeping the Genus, Species, and Accession constraints: OK, as long as it can be made clear to the user that either a gene ID or a Pangene ID is required.

Honestly it was never clear to me until just now these parameters are required. Wouldn't it accommodate more use cases  if these parameters weren't required?

**Comment by StevenCannon-USDA** [comment]
>Wouldn't it accommodate more use cases if these parameters [gene ID or a Pangene ID] weren't required?

I don't think so. The point of this search is to find "equivalent" genes (genes that share homology and position in some sense). A pangene set holds "equivalent" genes. There are only two meaningful kinds of queries: a gene or a pangene set (aka Pangene ID). The gene will be much more common.

Genus, species, or accession would only be useful as filters on the list of genes in a pangene set. I am still tempted to drop these secondary filters altogether.

**Comment by adf-ncgr** [comment]
> Display a pangene's gene set in a modal rather than directly in the results table
Is there a reason why we need this UI to involve a paginated results table at all? It seems like it's basically going to be retrieving a single PanGeneSet either based on the set id itself or a member gene id, but should not return multiple (unless we start supported multiple pangeneset builds).

It would be different (and possibly more interesting) if we had a search that would look for PanGeneSets according to their properties (e.g. return pangenesets with fewer than 6 accessions represented or having members from wild species but not from cultivated, etc.).

This query seems a little more like a lookup than a query (not that there's anything wrong with that!)

**Comment by adf-ncgr** [comment]
I guess an alternative view would be to make the things in the paginated results not be the PanGeneSet but the genes that are its members, maybe that's what @StevenCannon-USDA originally had in mind (and that would make filters by genus/species/accession more appropriate too)

**Comment by alancleary** [comment]
> I guess an alternative view would be to make the things in the paginated results not be the PanGeneSet but the genes that are its members, maybe that's what @StevenCannon-USDA originally had in mind (and that would make filters by genus/species/accession more appropriate too)

Yeah, I think this was the original intent of the spec, now that (I think) I understand it. This is still a finite set of data, though, so I think it would be more interesting to create a dedicated pangene page that we can put any sort of content related to a specific pangene in.

**Comment by sammyjava** [comment]
I doubt very many users would know our pan-gene set IDs (or gene family IDs for that matter), but there's certainly no reason not to include pan-gene set ID (or "pangene ID" if you will) on the gene search. The support for it was added to graphql-server a week or so ago.

**Comment by StevenCannon-USDA** [comment]
Sorry to be slow responding. I don't mind moving ahead with your proposal, @alancleary - i.e., 
>
- Pull in all the genes for each pangene set
...
- Display a pangene's gene set in a modal rather than directly in the results table
...

There is an interplay between the design vision and the  implementation constraints and affordances. 

Let me know if there is something needed from me at this point.

**Comment by alancleary** [comment]
@StevenCannon-USDA Perhaps this should be an agenda item for Wednesday, if we're meeting. The modal is no longer relevant now that (I think) I understand what you're proposing. At this point I think we should be able to achieve the pangene "search" you've described in two independent ways: 1) via the existing gene search and 2) via a pangene set search similar to what @adf-ncgr described.
