### ISSUE TITLE
Pull request template for making a release

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/graphql-server#93]
This issue is based on a discussion in PR #67. Basically there's a handful of steps that need to be taken when making a release. We want to capture these steps in a pull  request template so that the PR for a new release helps whoever is in charge of the PR make sure they took all the necessary steps. Here are the steps I've remembered so far (order matters)!

0. Open a PR for the release.
1. Update the dependencies. The dependabot PR backlog is not comprehensive and doesn't include transitive dependencies, and merging them one at a time tends to break things, so the best way to do this is manually with npm in a separate branch.
2. Bump the `intermineVersion` in `data-sources/intermine/api/index.ts` if appropriate.
3. Update the base image version in the Dockerfile if necessary (this should be the most recent node LTS version) and do a test build and run of the Docker image on you local machine so you know if something is going to go off the rails before the automated build action on GitHub.
4. Update the GHCR image tag in `compose.prod.yml` to the imminent release version
5. Bump the version number in `package.json`.
8. Merge the release PR.
9. Tag a release on GitHub with a new version tag that matches the version you specified in steps 4 and 5. This will trigger an automated Docker image build on GitHub. If the build succeeds it will be automatically published to GHCR.

This template is only for release PRs so it should not be setup as the default for all PRs. See the [GitHub docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) for details.

**Comment by sammyjava** [comment]
Gentle nudge: I'd really like to get the 5.1.0.3-model-changes branched merged into main soon, since the main branch is technically incorrect for the current production mines (and we're lucky in that it doesn't matter this time around). I'm interpreting from your self-assignment on this task that you'll put together the PR template (I deleted my start since it wasn't set up for only release PRs).

I am wondering how we will handle the juggle in the future when there is a mine update that requires a graphql-server update that requires a web-components update. Updates are _generally_ back-compatible like this one, but presumably they won't always be.

Updating the repos in a swell foop isn't hard, but then there's getting the various "users" to update their various Jekyll sites and graphql servers.
